### ISSUE TITLE
Handle SMTP in containerized Wordpress

### ISSUE THREAD

**Issue by spelkey-ucd** [UCDavisLibrary/main-wp-website#24]
Does not come with default wp image.

see: https://github.com/docker-library/wordpress/issues/30

**Comment by jrmerz** [comment]
Currently Looking to use wp plugin to directly handle SMTP in Wordpress.  Some candidates:

- https://wordpress.org/plugins/smtp-mailer
- https://wordpress.org/plugins/wp-smtp

Working with James on testing out this option
