### ISSUE TITLE
Issue with searching news items

### ISSUE THREAD

**Issue by NeilWeingarten** [UCDavisLibrary/main-wp-website#43]
Per Jessica-

We noticed that site search seems to have retained / still be indexing all the prior loads of the News. So if, for example, you do a [site search for "uc springer agreement](https://stage.library.ucdavis.edu/?s=uc+springer+agreement)", the first four results are all the same headline - but only one is the "real" news post; I assume the other three are ghosts from the prior loads of News. Reminiscent of the issue with UCLA guides still being indexed... so hopefully not too hard to fix?

**Comment by jrmerz** [comment]
This was just cruft left over from old bug with indexer that has already been patched.  I just reindexed to clean out cruft.
