### ISSUE TITLE
Special Collections hours update

### ISSUE THREAD

**Issue by NeilWeingarten** [UCDavisLibrary/main-wp-website#46]
Special collections hours need to be updated on the hours page to show both the appt link and their open hours through libcal.  See attached image for wireframe.

![Image](https://user-images.githubusercontent.com/17069741/181641851-1990e3f0-c956-43db-8164-1f0d2d569c5a.png)

**Comment by NeilWeingarten** [comment]
Image for homepage hours:

![Image](https://user-images.githubusercontent.com/17069741/181642137-5c9ff209-aaf0-48fb-b5d3-ee2ce426a593.png)

**Comment by spelkey-ucd** [comment]
These changes are off the table for launch. Multiple hour ranges for a given day are not currently supported, and would be a significant feature request.

**Comment by NeilWeingarten** [comment]
Ok - I'll add it to the post-live list and Jenny know.  Let's stall this issue in the meantime

**Comment by spelkey-ucd** [comment]
moved to https://github.com/UCDavisLibrary/ucdlib-wp-plugins/issues/150
