### ISSUE TITLE
install caching plugin

### ISSUE THREAD

**Issue by spelkey-ucd** [UCDavisLibrary/main-wp-website#56]

**Comment by qjhart** [comment]
Hummingbird is currently set to not cache the front page, and news page.  Default caching/not-caching is managed at the page type level.  But there are twig level commands that can be used to also enable/disable the cache.

**Comment by spelkey-ucd** [comment]
I found that the best settings combination is to enable caching for all page types, but to turn on the `clear full cache when post/page is updated`

![image](https://user-images.githubusercontent.com/34284106/185138019-becbbb85-6782-4a6a-ab17-c73fdfe7a613.png)

**Comment by qjhart** [comment]
@spelkey-ucd, our rollout yesterday showed that with front page and home caching on, new news items weren't breaking the cache, and so they would never show up.  There are probably other examples, (like the A-Z collections) that might also be affected that way.

**Comment by spelkey-ucd** [comment]
@qjhart yes, that makes sense. As of this morning, the above setting was off.

**Comment by qjhart** [comment]
Thanks for the catch.
