### ISSUE TITLE
Website redirect needed for person pages

### ISSUE THREAD

**Issue by UcDust** [UCDavisLibrary/main-wp-website#63]
On https://digital.ucdavis.edu/about it looks like the links to person pages are pointing to URLs like-
https://library.ucdavis.edu/author/peter-brantley/

However on the new site the page is really-
https://library.ucdavis.edu/person/peter-brantley/

Can we add a link redirect so these links resolve to a page?

**Comment by qjhart** [comment]
Added 


![Image](https://user-images.githubusercontent.com/344953/188718506-b104b1f5-f685-4941-83c3-479ee9024de9.png)
