### ISSUE TITLE
Permalinks not updating

### ISSUE THREAD

**Issue by NeilWeingarten** [UCDavisLibrary/main-wp-website#68]

**Comment by NeilWeingarten** [comment]
Some exhibits are unable to have their permalinks updated to remove the number at the end of the url.  Exhibits are:

- https://stage.library.ucdavis.edu/exhibit/california-in-song-3/
- https://stage.library.ucdavis.edu/exhibit/celebrating-century-biological-agricultural-engineering-department-2/
- https://stage.library.ucdavis.edu/exhibit/picnic-day-by-the-decade-2/
- https://stage.library.ucdavis.edu/exhibit/saratoga-horticultural-research-foundation-2/
- https://stage.library.ucdavis.edu/exhibit/the-california-aggie-photo-archives-gems-of-student-photojournalism-2/
- https://stage.library.ucdavis.edu/exhibit/ray-hunold-photograph-collection-storytellers-nature-photography-2/
- https://stage.library.ucdavis.edu/exhibit/unitrans-40-moving-students-decades-2/
-

**Comment by qjhart** [comment]
Permalinks are strange in the fact that the final name of the link can't overlap with any media type.  You can see that 

- https://stage.library.ucdavis.edu/california-in-song/
- https://stage.library.ucdavis.edu/celebrating-century-biological-agricultural-engineering-department/
- https://stage.library.ucdavis.edu/picnic-day-by-the-decade/
- https://stage.library.ucdavis.edu/saratoga-horticultural-research-foundation/
- https://stage.library.ucdavis.edu/the-california-aggie-photo-archives-gems-of-student-photojournalism/
- https://stage.library.ucdavis.edu/ray-hunold-photograph-collection-storytellers-nature-photography/
- https://stage.library.ucdavis.edu/unitrans-40-moving-students-decades/

- https://library.ucdavis.edu/california-in-song/
- https://library.ucdavis.edu/celebrating-century-biological-agricultural-engineering-department/
- https://library.ucdavis.edu/picnic-day-by-the-decade/
- https://library.ucdavis.edu/saratoga-horticultural-research-foundation/
- https://library.ucdavis.edu/the-california-aggie-photo-archives-gems-of-student-photojournalism/
- https://library.ucdavis.edu/ray-hunold-photograph-collection-storytellers-nature-photography/
- https://library.ucdavis.edu/unitrans-40-moving-students-decades/

**Comment by NeilWeingarten** [comment]
California in song update worked - all exhibits fixed.  Thanks!  Closing this issue
