### ISSUE TITLE
Rethink Dynamic Page Identification

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/main-wp-website#72]
Working from a suggestion of Steve's that adding a '?' via redirections allowed for the system to turn off caching, we created a set of redirections for the main website.  However, it appears that a ~?~ alone does not satisfy this: 

```bash
curl 'https://library.ucdavis.edu/directory/?' 2>/dev/null | head
```

```html
<!-- This page is cached by the Hummingbird Performance plugin v3.3.4 - https://wordpress.org/plugins/hummingbird-performance/. -->
  <!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="UTF-8" />
    <meta name="description" content="">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="author" href="https://library.ucdavis.edu/wp-content/themes/ucdlib-theme-wp/theme/humans.txt" />
```

An alternative is to just add these to the Hummingbird **Exclusions** setup,  and eliminate the current redirections that perform this setup.

![image](https://user-images.githubusercontent.com/344953/197639463-42e0ab97-0162-4717-8fda-9a62e2fdeabb.png)

These are my suggestions:

```text
wp-.*\.php
index\.php
xmlrpc\.php
sitemap[^\/.]*\.xml
^\/directory
^\/sign\/shields-hours
^\/archives-and-special-collections\/our-collections\/university-archives\/university-archives-collections
^\/archives-and-special-collections\/collection-subject
```

This example is currently implemented on stage:

```bash
curl 'https://stage.library.ucdavis.edu/directory/' 2>/dev/null | head
```

``` html
  <!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="UTF-8" />
    <meta name="description" content="Stage">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="author" href="https://stage.library.ucdavis.edu/wp-content/themes/ucdlib-theme-wp/theme/humans.txt" />
```

**Comment by mjwdavis** [comment]
Looking at staging, this seems to work, and I suppose the only consideration here is that we accept the performance hit in the page. I suspect that most of the people using this page will be other employees instead of users of the library.

One more thought- does caching of the page type 'People' (slug - 'person') also affect caching here, since the diretory is pulling content from that content type?

**Comment by qjhart** [comment]
@mjwdavis  Well, I guess the idea is that we always need to render  that page, so the hit is inevitable.  
@spelkey-ucd is better to answer your 2nd question, but my feeling is that the /directory/ page is rendered server-side twig style, and so the caching would hide updates that were made to the person info, even though the person's individual page will have updated.

**Comment by mjwdavis** [comment]
1. Disabled redirect on production.
2. Added rule to production hummingbird cache to ignore and dynamically render.

**Comment by mjwdavis** [comment]
@qjhart  - I've made the changes to /directory, but do you also want the following?:

`^\/directory
^\/sign\/shields-hours
^\/archives-and-special-collections\/our-collections\/university-archives\/university-archives-collections
^\/archives-and-special-collections\/collection-subject`

**Comment by qjhart** [comment]
@mjwdavis Yes, I think for consistency we do them all, and disable those all in the current redirection list.

**Comment by mjwdavis** [comment]
@qjhart - also done
