### ISSUE TITLE
Remove past employee profiles from site search

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/main-wp-website#76]
Directory Profile settings have an option to mark a person as no longer employed at the library in order to hide them from the directory and unlink their profile while maintaining the name credit display in places like Exhibits ([example](https://library.ucdavis.edu/exhibit/bradbury-family-papers-mexican-american-familys-story-1876-1965/)).

![Screen Shot 2022-08-29 at 3 41 02 PM](https://user-images.githubusercontent.com/17831969/187311547-e9fda891-aa0a-462e-8d4c-5ff5c0041162.png)

This all works fine **except** that the profiles still show up in the site search. 

[Example search for Jullianne](https://library.ucdavis.edu/?s=jullianne):

![Screen Shot 2022-08-29 at 3 48 51 PM](https://user-images.githubusercontent.com/17831969/187312217-fd1fb5d8-c4f7-44c2-979a-9e8972534433.png)

[Jullianne's profile](https://library.ucdavis.edu/person/jullianne-ballou/) is empty since in this case it was only created to allow us to credit her past work for the library. We don't want people to stumble across these empty pages via search, so they should be removed from the search results much like they are from the directory.

**Comment by spelkey-ucd** [comment]
When indexing the person post type, need to first check for pastEmployee metadata field. if checked, should not index person/remove them from index if they are already in it.

**Comment by spelkey-ucd** [comment]
deployed in main-wp-website:v3.3.0
